services:
  - type: web
    name: pie-backend-update
    runtime: node
    region: virginia
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: REFRESH_TOKEN_EXPIRY
        value: 10d
      - key: OTP_LENGTH
        value: 6
      - key: OTP_EXPIRY
        value: 10
      - key: OTP_ATTEMPTS
        value: 5
    healthCheckPath: /healthz
